# Generated by Django 3.2.7 on 2021-10-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_capsule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizerinrule',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fertilizerinslot',
            name='name',
        ),
        migrations.AddField(
            model_name='capsule',
            name='went_speed',
            field=models.FloatField(default=2000),
            preserve_default=False,
        ),
    ]
