# Generated by Django 3.2.7 on 2021-10-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_capsule', '0002_auto_20211002_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capsule',
            old_name='temprature',
            new_name='temperature',
        ),
        migrations.RenameField(
            model_name='fertilizerinrule',
            old_name='how_mutch',
            new_name='how_much',
        ),
    ]
