# Generated by Django 3.2.7 on 2021-10-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_capsule', '0003_auto_20211002_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizerinslot',
            name='is_turn_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planttype',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='plant_types_image/'),
        ),
    ]
